name: plot StaImage

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      YEAR : '2024'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Remove folder
        run: rm -rf ./OUT_FOLDER
      - name: Plot test image
        run: |
          python -u scripts/plotImage.py