name: read time sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
      YEAR : '2024'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Remove folder
        run: rm -rf ./OUT_FOLDER
      - name: Plot test image
        run: |
          python -u scripts/plotImage.py